export const BoardState = [
	[
		{ team: 'b', piece: 'r', x: 'a', y: 8 },
		{ team: 'b', piece: 'n', x: 'b', y: 8 },
		{ team: 'b', piece: 'b', x: 'c', y: 8 },
		{ team: 'b', piece: 'q', x: 'd', y: 8 },
		{ team: 'b', piece: 'k', x: 'e', y: 8 },
		{ team: 'b', piece: 'b', x: 'f', y: 8 },
		{ team: 'b', piece: 'n', x: 'g', y: 8 },
		{ team: 'b', piece: 'r', x: 'h', y: 8 },
	],
	[
		{ team: 'b', piece: 'p', x: 'a', y: 7 },
		{ team: 'b', piece: 'p', x: 'b', y: 7 },
		{ team: 'b', piece: 'p', x: 'c', y: 7 },
		{ team: 'b', piece: 'p', x: 'd', y: 7 },
		{ team: 'b', piece: 'p', x: 'e', y: 7 },
		{ team: 'b', piece: 'p', x: 'f', y: 7 },
		{ team: 'b', piece: 'p', x: 'g', y: 7 },
		{ team: 'b', piece: 'p', x: 'h', y: 7 },
	],
	[
		{ team: '', piece: '', x: 'a', y: 6 },
		{ team: '', piece: '', x: 'b', y: 6 },
		{ team: '', piece: '', x: 'c', y: 6 },
		{ team: '', piece: '', x: 'd', y: 6 },
		{ team: '', piece: '', x: 'e', y: 6 },
		{ team: '', piece: '', x: 'f', y: 6 },
		{ team: '', piece: '', x: 'g', y: 6 },
		{ team: '', piece: '', x: 'h', y: 6 },
	],
	[
		{ team: '', piece: '', x: 'a', y: 5 },
		{ team: '', piece: '', x: 'b', y: 5 },
		{ team: '', piece: '', x: 'c', y: 5 },
		{ team: '', piece: '', x: 'd', y: 5 },
		{ team: '', piece: '', x: 'e', y: 5 },
		{ team: '', piece: '', x: 'f', y: 5 },
		{ team: '', piece: '', x: 'g', y: 5 },
		{ team: '', piece: '', x: 'h', y: 5 },
	],
	[
		{ team: '', piece: '', x: 'a', y: 4 },
		{ team: '', piece: '', x: 'b', y: 4 },
		{ team: '', piece: '', x: 'c', y: 4 },
		{ team: '', piece: '', x: 'd', y: 4 },
		{ team: '', piece: '', x: 'e', y: 4 },
		{ team: '', piece: '', x: 'f', y: 4 },
		{ team: '', piece: '', x: 'g', y: 4 },
		{ team: '', piece: '', x: 'h', y: 4 },
	],
	[
		{ team: '', piece: '', x: 'a', y: 3 },
		{ team: '', piece: '', x: 'b', y: 3 },
		{ team: '', piece: '', x: 'c', y: 3 },
		{ team: '', piece: '', x: 'd', y: 3 },
		{ team: '', piece: '', x: 'e', y: 3 },
		{ team: '', piece: '', x: 'f', y: 3 },
		{ team: '', piece: '', x: 'g', y: 3 },
		{ team: '', piece: '', x: 'h', y: 3 },
	],
	[
		{ team: 'w', piece: 'p', x: 'a', y: 2 },
		{ team: 'w', piece: 'p', x: 'b', y: 2 },
		{ team: 'w', piece: 'p', x: 'c', y: 2 },
		{ team: 'w', piece: 'p', x: 'd', y: 2 },
		{ team: 'w', piece: 'p', x: 'e', y: 2 },
		{ team: 'w', piece: 'p', x: 'f', y: 2 },
		{ team: 'w', piece: 'p', x: 'g', y: 2 },
		{ team: 'w', piece: 'p', x: 'h', y: 2 },
	],
	[
		{ team: 'w', piece: 'r', x: 'a', y: 1 },
		{ team: 'w', piece: 'n', x: 'b', y: 1 },
		{ team: 'w', piece: 'b', x: 'c', y: 1 },
		{ team: 'w', piece: 'q', x: 'd', y: 1 },
		{ team: 'w', piece: 'k', x: 'e', y: 1 },
		{ team: 'w', piece: 'b', x: 'f', y: 1 },
		{ team: 'w', piece: 'n', x: 'g', y: 1 },
		{ team: 'w', piece: 'r', x: 'h', y: 1 },
	],
]
